os: linux
dist: trusty
language: java
install: skip
jdk:
- openjdk17
script:
- "./gradlew build"
- "./gradlew check"
- "./gradlew jar"
- "./gradlew publish"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: M1XbHNpVUSUNR0rS+heZ+fDl+6HX3obzMdwbOw6eOgPFjtu1SAImgbqeMILL3IYASe9YhGQZdh8Np6K1lQV/I63o6lQmbH7hrt8mfnbOif/jcGa+nDeeh4c16wV+MqG5FjaaPeL6nWGTCs+F/5WDCq1erh38STam6+iynJyfkp495/TZlgOhzI7Zte2POyGysgO2RUWhbGX3jyuNPu4xICu/5yTcp8BDOz2JaSyue4vR4L0xfud4KicdCk1YMO/0HJsu9RaRypZspfKH5p5JvomecQORb8U7ILfWCQzugbRk7kLz5DcFsoIgNDj1p54OJuAQvL0/rrFbA+Rg5dNqrqslON8b3ECgDbikjuYRZVTPa9+xM7t/yJ8Y712npXaKDR21UGBu+f1iYeMHsF3ElazxJ1o9m6TjZMdX1zthuoc50sYME49kGTrvgeYpyuP6X+p1QuZ0H6ct9UHa4Zs+ExSDj4bulRYxcFynbhR0YOeRX+FBuUd11KHEkfhyVRPLuXwgmyM4Gn3kJbl84QKECU/5w0NzL4uP0OTYQxQmMIzyQkGc84Iaspnx+1ygaevNPzoeHyVRj4/iEhdZXrwS3G54qvxJ5tXB+6esnnBre5DphdSYGEB44UMsUTqqG790fRxWhymU9Zs9IsNF5p/nIEHMas+B5sid/SxSBlEx40U=
